# @format

version: "3.8"

services:
    readwise-mcp-server:
        build: .
        container_name: readwise-mcp-http-server
        ports:
            - "3456:3000"
        env_file:
            - .env
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        volumes:
            # Mount logs directory if you want to persist logs
            - ./logs:/app/logs
        networks:
            - readwise-network

networks:
    readwise-network:
        driver: bridge
