# @format

version: "3.8"

services:
    readwise-mcp-server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: readwise-mcp-http-server-dev
        ports:
            - "3456:3000"
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            # Mount source code for hot reloading
            - ./src:/app/src
            - ./package.json:/app/package.json
            - ./tsconfig.json:/app/tsconfig.json
            - ./logs:/app/logs
        networks:
            - readwise-network-dev

networks:
    readwise-network-dev:
        driver: bridge
